language: python

# Runs jobs on container based infrastructure
sudo: false

# Saves pip downloads/wheels between builds
cache:
  directories:
    - $HOME/.cache/pip

python:
    - "3.6"

install:
    - pip install demjson
    - pip install -r tools/requirements.txt

script:
    - jsonlint defs/*.json
    - jsonlint defs/*/*.json
    - python tools/cointool.py check
    - python tools/support.py check --ignore-tokens --ignore-missing

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
